[package]
name = "partty"
version = "0.1.0"
edition = "2024"

[dependencies]
glyphon = "0.12"
pollster = "0.4"
portable-pty = "0.8"
sys-locale = "0.3"
serde = { version = "1", features = ["derive"] }
toml = "0.8"
vte = "0.15.0"
wgpu = "30"
winit = "0.30"
arboard = "3.6.1"
base64 = "0.23.1"
image = "0.25.10"
